### ISSUE TITLE
[Question] Keep By Tag?

### ISSUE THREAD

**Issue by nr-pushan** [GoogleCloudPlatform/gcr-cleaner#105]
Hello!

I have just discovered this tool.

Is it possible to keep all images with a specific tag? For example, I want GCR Cleaner to delete all images except the image with the "latest" tag.

What command do I pass to make that happen? If possible?

**Comment by porjo** [comment]
I think this is the same as #65

**Comment by sethvargo** [comment]
Duplicate of #65
