### ISSUE TITLE
GitHub Actions - I've been waiting for a long time！？

### ISSUE THREAD

**Issue by iwangxiaodong** [GoogleCloudPlatform/gcr-cleaner#109]
![QQ截图20221008054900](https://user-images.githubusercontent.com/16535878/194668018-ea3927c6-af08-4a6d-bd6e-0a35574fafaf.png)

Deploy GCR Cleaner to GitHub Actions

I've been waiting for a long time！ Why？

Please help me. Thanks.

**Comment by iwangxiaodong** [comment]
![QQ截图20221008060051](https://user-images.githubusercontent.com/16535878/194668794-d30c689b-3512-4802-9976-64218a6f7915.png)

my github actions config file.

**Comment by sethvargo** [comment]
You are running the gcr-cleaner server. You need to use the gcr-cleaner CLI. See https://github.com/GoogleCloudPlatform/gcr-cleaner/blob/main/docs/deploy-github-actions.md.

**Comment by iwangxiaodong** [comment]
It works！ Thank you!
