### ISSUE TITLE
[Question] GCP artifacts

### ISSUE THREAD

**Issue by TriPSs** [GoogleCloudPlatform/gcr-cleaner#122]
Hi, first of all thanks for this action! 

I have a question regarding cleanup in gcp artifacts. If I open the artifacts in GCP console there is a `<name>` one and a `<name>/cache`, this it cleanup both or only the `<name>` one?

**Comment by sethvargo** [comment]
By default, it will only clean up `<name>`. If you specify `-recursive`, it will do both.

**Comment by TriPSs** [comment]
Thanks!

**Comment by TriPSs** [comment]
Forgot to ask my followup: If `-recursive` is also enabled and `/cache` is also cleared, this will only slow down the next build right? Since that cache layer will then be removed?
