### ISSUE TITLE
Difference between docs and  and help pages and expected behavior

### ISSUE THREAD

**Issue by grabango-ttharp** [GoogleCloudPlatform/gcr-cleaner#136]
### TL;DR

Running command with -dry_run=true command results in failure. Docs show that command is -dry_run=true command that works is -dry-run=true
Help page also shows that the proper command is -dry-run

### Expected behavior

-dry-run=true should be changed in docs

### Observed behavior

-dry_run=true does not work

### Debug log output

```text
docker run -it us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli -repo=gcr.io -dry_run=true
flag provided but not defined: -dry_run
Usage of /bin/gcr-cleaner-cli:

  Deletes untagged or stale images from a Docker registry.
```

**Comment by sethvargo** [comment]
Hi @grabango-ttharp 

[None of the documentation in this repo suggests using "dry_run=true" on the CLI](https://github.com/GoogleCloudPlatform/gcr-cleaner/search?q=dry_run%3Dtrue). I believe you're referring to the [Server Payload & Parameters](https://github.com/GoogleCloudPlatform/gcr-cleaner#server-payload--parameters), which has the following warning at the top:

> ⚠️ This section is for the server payload. If you are using the CLI tool, run `gcr-cleaner -h` to see the list of flags and their descriptions.

As the warning implies, please run `gcr-cleaner -h` to see the full list of CLI flags and that pertain to the version of gcr-cleaner that you have downloaded.
