### ISSUE TITLE
Feature: support internal cloud run ingress

### ISSUE THREAD

**Issue by dindurthy** [GoogleCloudPlatform/gcr-cleaner#147]
Can the [Cloud Run implementation](https://github.com/GoogleCloudPlatform/gcr-cleaner/blob/main/docs/deploy-cloud-run.md) be enhanced to support an internal cloud ingress, possibly even as the default? The Cloud Schedule cron --> Cloud Run implementation shouldn't need to public as far as I can tell.

[Example commit.](https://github.com/100health/terraform-google-gcr-cleaner/commit/0ab6f5036e86d3dd4a13482c38d937f8b7de3a84)

**Comment by sethvargo** [comment]
Hi @dindurthy - unless something has changed recently, Cloud Scheduler is not a VPC-native service. It's not on the VPC and therefore would not satisfy the constraints for "internal" load balancing.
