### ISSUE TITLE
Tag filter is applied only to first tag

### ISSUE THREAD

**Issue by tenevdev** [GoogleCloudPlatform/gcr-cleaner#54]
The current behaviour when using tag filter is to compare it against the first tag of each image.

This matters for use cases on images with multiple tags.

In my view, it is more intuitive to have an option to say it should match any of the tags on the image or all of the tags on the image.
If you care about backwards compatibility (i.e. this was a feature and not a bug), there could also be an option to only match the first tag...

In my particular use case, the image should be deleted only if the filter to matches all the tags on the image. I actually think this is the most sensible default for the library because it's the most strict (matches the least) which is a good idea when the effect of the operation is permanent deletion.

**Comment by sethvargo** [comment]
The reason I went with checking the first tag was:

- Across (public) Container Registry and Docker Registry at the time, only 14% of tagged images had more than one tag. This could have changed since, but it didn't seem like there were a compelling number of images being multi-tagged.
- The logic to an end-user becomes incredibly confusing: Do I want to delete iff _all_ tags match? Do I want to delete iff _any_ tags match? There's another thread about inverse matches (only when tags _don't_ match), in which case how would users expect the logic to be inverted?

**Comment by danielharr** [comment]
> Across (public) Container Registry and Docker Registry at the time, only 14% of tagged images had more than one tag. This could have changed since, but it didn't seem like there were a compelling number of images being multi-tagged.

I fail to see how this motivates not implementing this, when there is a demand?

> The logic to an end-user becomes incredibly confusing: Do I want to delete iff all tags match? Do I want to delete iff any tags match? There's another thread about inverse matches (only when tags don't match), in which case how would users expect the logic to be inverted?

IMHO it is more confusing that the filter only applies to the first tag. Would the cases you're describing rather not require a less restrictive filter, or a "match any" feature which considers all tags?

**Comment by sethvargo** [comment]
> I fail to see how this motivates not implementing this, when there is a demand?

There have been exactly 3 requests for this over the lifetime of the project, and GCR Cleaner is used millions of times each day. My point is that the complexity required to implement this correctly and in a backwards-compatible way, and I _don't_ think there's reasonable demand given existing use. That doesn't mean we'll never do it, it just means it hasn't been a priority.

> IMHO it is more confusing that the filter only applies to the first tag. Would the cases you're describing rather not require a less restrictive filter, or a "match any" feature which considers all tags?

The current behavior is predictable for all possible inputs, which was the goal. I think there's room for a more powerful filtering system (one that let's users express complex expressions), but that's going to require a design that maintains BC and supports all possible use cases; I don't want to engineer a stop-gap solution.
