### ISSUE TITLE
docs: tag_filter_any does not mention it will also match images without tags

### ISSUE THREAD

**Issue by thdk** [GoogleCloudPlatform/gcr-cleaner#69]
For some time, I thought I would need to run two scheduled jobs. One job to remove images without tags and another one where I would make use of the `tag_filter_any` or `tag_filter_all` to delete tagged images that match a certain pattern in the tag name.

However, I see in the source code that untagged images are always removed.

If this is correct I think this might be valuable information to add in the documentation.

**Comment by sethvargo** [comment]
Yea, it matches untagged images too.

**Comment by rjpeter2** [comment]
Which is good! Except, the `keep` logic includes the untagged images as well. I think this is undesired behavior.
If I have images tagged like so:
<>
<1.0.8><latest>
<1.0.7>
<1.0.6>
<1.0.5>
<>
Where <> are untagged images.
Then if I run a filter like so:
`-tag-filter-any "^(\d+).(\d+).(\d+)$" -keep 3`

I would expect it to delete the untagged images and image 1.0.5, keeping 1.0.8, 1.0.7, and 1.0.6. But this is not the case. It will delete 1.0.6, 1.0.5, and the untagged image after 1.0.5. This is not very glamorous but I think a solution that would fix this without a bunch of refactoring would be to change this line in [pkg/gcrcleaner/cleaner.go](https://github.com/GoogleCloudPlatform/gcr-cleaner/blob/main/pkg/gcrcleaner/cleaner.go#L83):
`if keepCount < keep {` to `if keepCount < keep && len(m.Tags) != 0 {`

Let me know if you'd like this change and I can whip up a PR.

**Comment by sethvargo** [comment]
I think the core of the issue is:

> the keep logic includes the untagged images as well...

And what the _right_ behavior is here. In my head, "keep" means keep N things, not keep N tagged things but delete everything else.
