### ISSUE TITLE
v0.7.1 release?

### ISSUE THREAD

**Issue by nWhitehill** [GoogleCloudPlatform/gcr-cleaner#73]
Hello.

On Jan 11 there was a [commit that fixed an output bug](https://github.com/GoogleCloudPlatform/gcr-cleaner/commit/834f5cbd90d6cde6b76ef90870e66556c666d982). I was wondering if we could get this released as a new bugfix version. I recently tried to use the tool and was very confused with my `dry_run` outputs showing not only multiple commits but occasionally showing commits that had labels on them still. 

Additionally, I would like to request a slight change to the fix. I have left the details in #72.

**Comment by sethvargo** [comment]
Done.
