### ISSUE TITLE
README.md Step 3 advises enabling App Engine -- is this necessary?

### ISSUE THREAD

**Issue by kashev** [GoogleCloudPlatform/gcr-cleaner#83]
Based on my reading of the description of the project, it's not clear to me why enabling the App Engine API for running gcr-cleaner is necessary. It seems like Scheduler and Cloud Run should be sufficient.

If I am understanding correctly, I'd be happy to submit the small PR to remove it from README.md step 3.

**Comment by sethvargo** [comment]
Cloud Scheduler is dependent on App Engine. Cloud Scheduler requires App Engine app created to setup the region, but it only needs GAE to initialize the regional info for the project, no other dependencies.

When you do this via the Cloud Console, it happens automatically. When using the API/CLI, you have to do it manually.
