### ISSUE TITLE
[Question] Running using community terraform module / cloud run result

### ISSUE THREAD

**Issue by mo3athi** [GoogleCloudPlatform/gcr-cleaner#95]
### TL;DR

After running it using cloudrun & cloudscheduler, I can't find any useful logs which show what's going on.
For instance when I enabled dry-run, I couldn't find the output! I only see that job has succeeded!

### Expected behavior

Getting the stdout

### Observed behavior

unuseful logs

**Comment by sethvargo** [comment]
Hi @mo3athi 

Make sure you've set a log level environment variable (`GCRCLEANER_LOG=debug`). Then the log messages will be for the _Cloud Run Service_, not the Cloud Scheduler job. You can find them in the Logs Viewer on the Google Cloud console.

**Comment by mo3athi** [comment]
@sethvargo Thank you so much!
I've managed to add through the gcp console, and it worked!
**is there any way to add it within the tf module ?**

**Comment by sethvargo** [comment]
Hi @mo3athi - I do not manage the Terraform module. You would need to contact the author.
