### ISSUE TITLE
ARM Architecture not supported

### ISSUE THREAD

**Issue by igoooor** [GoogleCloudPlatform/gcr-cleaner#96]
### TL;DR

ARM Architecture not supported

### Expected behavior

Docker container to run with ARM based architecture

### Observed behavior

Docker container does not run with ARM based architecture

### Debug log output

```text
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
```


### Additional information

_No response_

**Comment by sethvargo** [comment]
Hi @igoooor 

Docker multi-build doesn't seem to be well-supported, and there hasn't been much demand. I'll accept a community contribution for this feature, but it's not a core priority for the project right now.
